//
//  CourseListModels.swift
//  SwiftbookApp
//
//  Created by Евгений Карпов on 04.01.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias CourseCellViewModel = CourseList.ShowCourses.ViewModel.CourseCellViewModel

protocol CellIdentifiable {
    var cellIdentifier: String { get }
    var cellHeight: Double { get }
}

enum CourseList {
    // MARK: Use cases
    
    enum ShowCourses {
        struct Request {
        }
        
        struct Response {
            let courses: [Course]
        }
        
        struct ViewModel {
            struct CourseCellViewModel: CellIdentifiable {
                let name: String
                let imageURL: URL
                
                var cellIdentifier: String {
                    "CourseCell"
                }
                
                var cellHeight: Double {
                    100
                }
                
                init(course: Course) {
                    name = course.name
                    imageURL = course.imageUrl
                }
            }
            let rows: [CellIdentifiable]
        }
    }
}
